title: 产品
tabs:
  main:
    display: 主要的
    sections:
      -
        display: 内容
        fields:
          -
            handle: product_categories
            field:
              type: terms
              taxonomies:
                - product_categories
              display: 分类
              mode: select
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: 产品名称
          -
            handle: description
            field:
              type: textarea
              display: 摘要
          -
            handle: photo_group
            field:
              container: assets
              folder: products
              type: assets
              display: 产品图组
              restrict: true
          -
            handle: content
            field:
              remove_empty_nodes: false
              type: bard
              display: 产品详情
              container: assets
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - table
              sets:
                '':
                  display: 新集组
                  sets:
                    image_block:
                      display: 内容图片
                      fields:
                        -
                          handle: image
                          field:
                            container: assets
                            folder: products
                            type: assets
                            display: 插入图片
                            restrict: true
                        -
                          handle: description
                          field:
                            type: text
                            display: 图片描述
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        display: 设置
        fields:
          -
            handle: cover
            field:
              max_files: 1
              container: assets
              folder: products
              type: assets
              display: 封面
              restrict: true
          -
            handle: price
            field:
              type: float
              display: 价格
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - required
                - 'max:200'
              show_regenerate: true
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
